# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu"

  config.vm.network "private_network", ip: "192.168.33.11"

  #config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.box = "generic/ubuntu1804"
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install ubuntu-desktop -y
   SHELL
  
end